spring:
  application:
    name: offer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

management:
  observations:
    annotations:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

server:
  port: 8081

#micrometer:
#  observations:
#    annotations:
#      enabled: true