spring:
  application:
    name: offer-service

management:
  observations:
    annotations:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

server:
  port: 8081

#micrometer:
#  observations:
#    annotations:
#      enabled: true